### PR TITLE
Add Awattar Tibber features

### LINKED ISSUE #114: Missing features - set price
Maybe I'm stupid, but I can't find the setting for putting the price limit for when to charge from grid.
I see something that might be it, but is unavailable.. what do I need to do?

image

### PR DESCRIPTION
**Pull request by EmbeddedFiedel**
- Activated awe switch, as it is supported by new firmware
- Bugfix for awcp sensor
- Added awp number
- Added Code to differentiate set_native_value between int and float
- Updated Readme

This should fix #114

### CODE REVIEW

**Review by syssi — APPROVED** [review]
LGTM!

**Comment by Dr-Stevens** [comment]
I tried updating the files.. But I still have no luck enabling the Price change thingy.. can someone explain how I get this to work??

**Comment by EmbeddedFiedel** [comment]
You need to enable the entity, as it is deactivated per default.

image

**Comment by Dr-Stevens** [comment]
Fucking awesome! Thank you very much :)

**Comment by EmbeddedFiedel** [comment]
@syssi 
Thanks for merging. 
Could you create a release based on this change?

**Comment by syssi** [comment]
Sure! :-)

**Pull request merged**
